export const BATTLE_LEVELS = {
  levelNames: ['rookie stage', 'career climb', 'market master'],
};

// Fallback minimal questions (used if pools unavailable)
export const LEVELS = [
  [
    { q: 'You\'ve been saving $200/month for 6 months. Your friend says "wait for a market dip to invest." What\'s the best long-term habit?', a: ['Invest monthly (dollar-cost averaging)', 'Time the market and wait for dips'], correct: 0 },
    { q: 'You just got your first job paying $40,000/year. Your expenses are $2,500/month. How much should you keep in an emergency fund?', a: ['3–6 months of expenses ($7,500–$15,000)', '0–1 month ($0–$2,500)'], correct: 0 },
    { q: 'You have $5,000 saved and $8,000 in credit card debt at 24% APR. You also see a "hot stock tip" that could double your money. Should you prioritize paying off high-interest debt first?', a: ['Yes, pay off debt first (guaranteed 24% return)', 'No, invest in the hot stock tip'], correct: 0 },
    { q: 'Your coworker made $10,000 on a single tech stock and suggests you "go all-in" on it. Should you diversify your portfolio instead?', a: ['Yes, diversify across multiple stocks/ETFs', 'No, follow the hot tip and go all-in'], correct: 0 },
    { q: 'The market crashes -20% in one week. News headlines scream "RECESSION!" and your portfolio is down. Should you panic sell?', a: ['No, stay invested and stick to your plan', 'Yes, sell everything before it gets worse'], correct: 0 },
  ],
  [
    { q: 'Most diversified?', a: ['Single stock', 'Sector ETF', 'Total-market ETF'], correct: 2 },
    { q: 'Cost that matters long-term?', a: ['Expense ratio', 'Ticker length', 'Share price'], correct: 0 },
    { q: 'Balanced allocation?', a: ['100% stocks', '70/30', '100% bonds'], correct: 1 },
    { q: 'Smart dip response?', a: ['Panic sell', 'Buy/hold', 'Ignore forever'], correct: 1 },
    { q: 'Beginner strategy?', a: ['Options', 'Leveraged ETFs', 'Index fund DCA'], correct: 2 },
  ],
  [
    { q: 'Tax-advantaged priority?', a: ['Crypto wallet', 'Taxable first', 'HSA/401k/IRA first', 'Cash only'], correct: 2 },
    { q: 'Reduce idiosyncratic risk?', a: ['1 stock', '5 similar', '20 uncorrelated', 'Timing news'], correct: 2 },
    { q: 'Defensive asset?', a: ['Growth stocks', 'Long bonds', 'Junk bonds', 'Quality bonds'], correct: 3 },
    { q: 'Portfolio $1000 → $1150, %?', a: ['5%', '15%', '25%', '35%'], correct: 1 },
    { q: 'Sequence risk mitigate?', a: ['Lump-sum top', 'Stop', 'Diversification + DCA', 'All cash'], correct: 2 },
  ],
];

export const BATTLE_POOLS = {
  L1: [
    { q: 'You\'ve been saving $200/month for 6 months. Your friend says "wait for a market dip to invest." What\'s the best long-term habit?', a: ['Invest monthly (dollar-cost averaging)', 'Time the market and wait for dips'], correct: 0 },
    { q: 'You just got your first job paying $40,000/year. Your expenses are $2,500/month. How much should you keep in an emergency fund?', a: ['3–6 months of expenses ($7,500–$15,000)', '0–1 month ($0–$2,500)'], correct: 0 },
    { q: 'You have $5,000 saved and $8,000 in credit card debt at 24% APR. You also see a "hot stock tip" that could double your money. Should you prioritize paying off high-interest debt first?', a: ['Yes, pay off debt first (guaranteed 24% return)', 'No, invest in the hot stock tip'], correct: 0 },
    { q: 'Your coworker made $10,000 on a single tech stock and suggests you "go all-in" on it. Should you diversify your portfolio instead?', a: ['Yes, diversify across multiple stocks/ETFs', 'No, follow the hot tip and go all-in'], correct: 0 },
    { q: 'The market crashes -20% in one week. News headlines scream "RECESSION!" and your portfolio is down. Should you panic sell?', a: ['No, stay invested and stick to your plan', 'Yes, sell everything before it gets worse'], correct: 0 },
    { q: 'You\'re 22 and just started working. You can save $100/month now, or wait 2 years for a promotion to save $500/month. What\'s the best approach?', a: ['Start saving small amounts now (time in market matters)', 'Wait for the big bonus to start saving'], correct: 0 },
    { q: 'Your grandparent tells you: "If you invest $1,000 at age 20 at 7% returns, you\'ll have more at 65 than investing $1,000 at age 30." Is compound interest really that powerful?', a: ['Yes, starting early makes a huge difference', 'No, it doesn\'t matter when you start'], correct: 0 },
    { q: 'You notice you\'re spending $200/month on coffee and subscriptions, but you\'re not sure where else your money goes. Should you track your expenses?', a: ['Yes, track expenses to find savings opportunities', 'No, tracking is too much work'], correct: 0 },
    { q: 'You make $3,000/month after taxes. A financial blog suggests the 50/30/20 rule: 50% needs, 30% wants, 20% savings. Is this a good budget framework?', a: ['Yes, 50/30/20 is a solid starting point', 'No budget needed, just spend what you want'], correct: 0 },
    { q: 'You have a $2,000 credit card balance with 22% APR. You can pay the $50 minimum or the full $2,000. What should you do?', a: ['Pay in full each month (avoid interest)', 'Pay minimum only (keep cash for other things)'], correct: 0 },
    { q: 'You\'re 23 and retirement seems 40+ years away. Your friend says "start saving for retirement now, even $50/month." Should you start retirement saving early?', a: ['Yes, starting early gives you decades of compound growth', 'No, retirement is too far away to worry about'], correct: 0 },
    { q: 'Inflation is 3% per year. Your savings account pays 0.5% interest. Will your savings account beat inflation?', a: ['No, inflation erodes your purchasing power', 'Yes, savings accounts always beat inflation'], correct: 0 },
    { q: 'You want to start investing but don\'t know which stocks to pick. Your friend suggests index funds that track the whole market. Are index funds good for beginners?', a: ['Yes, index funds are simple and diversified', 'No, individual stocks are better for beginners'], correct: 0 },
    { q: 'Your portfolio started 70% stocks, 30% bonds. After a year, stocks grew faster and now it\'s 80% stocks, 20% bonds. Should you rebalance back to 70/30?', a: ['Yes, rebalance to maintain your target allocation', 'No, let winners keep running'], correct: 0 },
    { q: 'You see social media posts about people getting rich quick from crypto and meme stocks. What mindset should you adopt?', a: ['Patience and long-term investing', 'Quick riches and get-rich-quick schemes'], correct: 0 },
    { q: 'You got a $5,000 raise. Your friend suggests upgrading your apartment and buying a nicer car. Should you avoid lifestyle creep?', a: ['Yes, save/invest the extra instead of spending more', 'No, you earned it, spend it all'], correct: 0 },
    { q: 'Your job pays well, but you\'re wondering if you should start a side hustle or freelance work. Are multiple income streams valuable?', a: ['Yes, multiple income streams reduce risk', 'No, one job is enough'], correct: 0 },
    { q: 'You\'re healthy and 24 years old. Your friend says "you don\'t need health insurance, you\'re young!" Is insurance necessary?', a: ['Yes, unexpected medical costs can be devastating', 'No, insurance is a waste when you\'re young'], correct: 0 },
    { q: 'You\'re single with no kids and minimal assets. Your coworker mentions creating a will. Should you have a will or estate plan?', a: ['Yes, everyone should have basic estate planning', 'No, wills are only for old rich people'], correct: 0 },
    { q: 'You\'re confused about Roth vs Traditional IRAs, tax strategies, and asset allocation. When should you consider a financial advisor?', a: ['When you have complex needs or lack knowledge', 'Always DIY, advisors are scams'], correct: 0 },
    { q: 'Tax season is coming. You worked a side job and had some investment losses. Should you track tax deductions and document everything?', a: ['Yes, proper documentation saves money and prevents issues', 'No, the IRS will figure it out'], correct: 0 },
    { q: 'You have free time on weekends. Your friend makes $500/month from a side hustle. Is a side hustle valuable for building wealth?', a: ['Yes, side hustles can accelerate wealth building', 'No, side hustles are not worth the time'], correct: 0 },
    { q: 'You have three debts: $500 at 5% APR, $2,000 at 18% APR, and $1,000 at 22% APR. What\'s the best debt payoff strategy?', a: ['Pay smallest debt first (snowball method)', 'Pay highest interest first (avalanche method)'], correct: 1 },
    { q: 'You have $10,000 invested in stocks. Your friend says "keep some cash reserves for emergencies and opportunities." Are cash reserves important?', a: ['Yes, cash provides flexibility and safety', 'No, invest everything for maximum returns'], correct: 0 },
    { q: 'You want to "save more money" but that\'s vague. Your mentor says "set a specific goal like \'save $10,000 for a house down payment by age 28.\'" Is specific goal setting important in finance?', a: ['Yes, specific goals are more achievable', 'No, vague goals work just as well'], correct: 0 },
  ],
  L2: [
    { q: 'Most diversified?', a: ['Single stock', 'Sector ETF', 'Total-market ETF'], correct: 2 },
    { q: 'Cost that matters long-term?', a: ['Expense ratio', 'Ticker length', 'Share price'], correct: 0 },
    { q: 'Balanced allocation?', a: ['100% stocks', '70/30', '100% bonds'], correct: 1 },
    { q: 'Smart response to a dip?', a: ['Panic sell', 'Buy more or hold', 'Ignore forever'], correct: 1 },
    { q: 'Good beginner strategy?', a: ['Options', 'Leveraged ETFs', 'Index fund DCA'], correct: 2 },
    { q: 'Common retirement account?', a: ['401k', 'Savings jar', 'Checking'], correct: 0 },
    { q: 'Bond role in portfolio?', a: ['Growth', 'Stability', 'Speculation'], correct: 1 },
    { q: 'Dollar-cost averaging means?', a: ['Lump sum', 'Timed buys', 'Regular invests'], correct: 2 },
    { q: 'Volatility measure?', a: ['Beta', 'Alpha', 'Ticker'], correct: 0 },
    { q: 'Dividend focus?', a: ['Growth stocks', 'High-yield', 'Meme stocks'], correct: 1 },
    { q: 'Asset classes basic?', a: ['Stocks only', 'Stocks+Bonds+Real estate', 'Crypto only'], correct: 1 },
    { q: 'Bear market strategy?', a: ['Sell all', 'Hold+Buy', 'Ignore'], correct: 1 },
    { q: 'P/E ratio indicates?', a: ['Overvalued if high', 'Undervalued if high', 'Irrelevant'], correct: 0 },
    { q: 'Roth vs Traditional?', a: ['Tax now', 'Tax later', 'No tax'], correct: 0 },
    { q: 'Emergency fund location?', a: ['High-yield savings', 'Under mattress', 'Stocks'], correct: 0 },
    { q: 'Credit score factor?', a: ['Payment history', 'Fav color', 'Age'], correct: 0 },
    { q: 'Mutual fund vs ETF?', a: ['Active manage', 'Passive low-cost', 'High-fee'], correct: 1 },
    { q: 'Inflation hedge?', a: ['Cash', 'Gold', 'Bonds only'], correct: 1 },
    { q: 'Risk tolerance?', a: ['Age-based', 'Random', 'Always aggressive'], correct: 0 },
    { q: 'Fiduciary advisor?', a: ['Client first', 'Sales first', 'Friend advice'], correct: 0 },
    { q: 'Compound calc simple?', a: ['On principal', 'On interest too', 'Flat rate'], correct: 1 },
    { q: 'Market cap means?', a: ['Company size', 'Share price', 'Employee count'], correct: 0 },
    { q: 'S&P 500 tracks?', a: ['Broad market', 'Single sector', 'International'], correct: 0 },
    { q: 'Budget app use?', a: ['Track spending', 'Ignore', 'Manual only'], correct: 0 },
    { q: 'Tax-loss harvesting?', a: ['Sell losers for tax', 'Buy winners', 'Hold forever'], correct: 0 },
  ],
  L3: [
    { q: 'Tax-advantaged priority?', a: ['Crypto wallet', 'Taxable first', 'HSA/401k/IRA first', 'Cash only'], correct: 2 },
    { q: 'Reduce idiosyncratic risk?', a: ['1 stock', '5 similar', '20 uncorrelated', 'Timing news'], correct: 2 },
    { q: 'Defensive asset?', a: ['Growth stocks', 'Long-duration bonds', 'Junk bonds', 'Quality bonds'], correct: 3 },
    { q: 'Portfolio $1000 → $1150, % change?', a: ['5%', '15%', '25%', '35%'], correct: 1 },
    { q: 'Mitigate sequence risk?', a: ['Lump-sum at top', 'Stop investing', 'Diversification + DCA', 'All cash'], correct: 2 },
    { q: 'Efficient frontier?', a: ['Optimal risk-return', 'Max risk', 'Min return', 'Random picks'], correct: 0 },
    { q: 'Sequence risk in retirement?', a: ['Early bad returns hurt', 'Late bad ok', 'No impact', 'Always good'], correct: 0 },
    { q: '$5000 at 7% for 10y ≈?', a: ['$7500', '$9835', '$10000', '$19671'], correct: 1 },
    { q: 'Alternative investments?', a: ['Art+Wine', 'Stocks only', 'Bonds only', 'Cash'], correct: 0 },
    { q: 'Sharpe ratio measures?', a: ['Risk-adjusted return', 'Total return', 'Volatility only', 'Price'], correct: 0 },
    { q: 'ESG focus?', a: ['Environmental+Social', 'Profits only', 'Government', 'Random'], correct: 0 },
    { q: 'Inflation 3% halves in ≈?', a: ['10', '24', '50', '100'], correct: 1 },
    { q: 'Monte Carlo does?', a: ['Predict outcomes', 'Guarantee returns', 'Time market', 'Ignore risk'], correct: 0 },
    { q: 'Annuity pros?', a: ['Guaranteed income', 'High growth', 'Low fees', 'Speculative'], correct: 0 },
    { q: 'Diversified return 50% +20%, 50% -10% = ?', a: ['5%', '10%', '15%', '0%'], correct: 0 },
  ]
};


